Beut 39 MemberRepository 테스트 코드 작성
BeutyNCuty/bnc pull request #26
Opened 2022-05-24 15:06 UTC by jy98102

2022-05-24 15:07 UTC, jungjaewonss approved these changes

2022-05-24 15:07 UTC, mumura approved these changes

2022-05-24 15:08 UTC, mumura approved these changes

2022-05-26 02:03 UTC, goyounha11 requested changes

2022-05-26 02:03 UTC, goyounha11 commented on src/main/java/com/bnc/main/member/controller/MemberRestController.java
> +
22번 23번 사이 공백추가해주시고 24번줄 공백 제거해주세요

2022-05-26 02:03 UTC, goyounha11 commented on src/main/resources/static/assets/js/member/join.js
> +});
이 의미없는 js분리는 뭐죠?

2022-05-26 02:03 UTC, goyounha11 commented on src/main/resources/templates/views/member/joinUser.html
> +
공백제거

2022-05-26 12:27 UTC, jy98102 commented on build.gradle
>      implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
콘솔에 파라미터값이 ?로 나타나는데 이 값을 나타내줘서 사용했어요

2022-05-26 12:30 UTC, jy98102 commented on src/main/resources/static/assets/js/member/join.js
> +});
6번 줄부터 25번 줄까지를 2번 안으로 넣으라는 건가요?

2022-05-27 02:15 UTC, goyounha11 commented on src/main/resources/static/assets/js/member/join.js
> +});
아뇨 html 파일안에 있으면되는데 굳이 js 분리할필요 있나요?

2022-05-27 04:12 UTC, merged