Beut 40 유저 조회 및 수정 api 개발
BeutyNCuty/bnc pull request #28
Opened 2022-05-30 14:43 UTC by wonhoc

2022-05-31 01:21 UTC, goyounha11 requested changes
전체적으로 많이 나아진 것 같습니다

2022-05-31 01:21 UTC, goyounha11 commented on src/main/java/com/bnc/main/member/controller/MemberRestController.java
> +    }
Detail이면 상세정보 조회인 것 같은데 Response가 Create? 이상하지 않나요?

2022-05-31 01:21 UTC, goyounha11 commented on src/main/java/com/bnc/main/member/domain/MemberRepository.java
>      int countByuserId(String userId);
카멜 지켜주세요
countByUserId

2022-05-31 01:21 UTC, goyounha11 commented on src/test/java/com/bnc/main/member/controller/MemberRestControllerTest.java
> +                .andDo(print());
get("/detailMember/{id}", req.getId()) 이렇게 해주세요

2022-05-31 01:21 UTC, goyounha11 commented on src/test/java/com/bnc/main/member/controller/MemberRestControllerTest.java
> +
Member 객체 생성인데 req라는 이름은 좀 그렇죠?
req는 뭔가 client로부터 요청 느낌이지 않나요?

2022-05-31 01:21 UTC, goyounha11 commented on src/test/java/com/bnc/main/member/controller/MemberRestControllerTest.java
> +
이것도 마찬가지구요

2022-05-31 01:21 UTC, goyounha11 commented on src/test/java/com/bnc/main/member/controller/MemberRestControllerTest.java
> +
위에서 req라고 해서 change 메서드가 마치 MemberUpdateRequest에 있나? 하는 생각이 드네요

2022-05-31 01:21 UTC, goyounha11 commented on src/test/java/com/bnc/main/member/controller/MemberRestControllerTest.java
> +                        jsonPath("$.member.phone").value("01054646464")
update한 것만 체크하는게 아니라 모든 것을 체크해주세요

2022-05-31 01:21 UTC, goyounha11 commented on src/test/java/com/bnc/main/member/domain/MemberRepositoryTest.java
List 앞에 공백제거

2022-05-31 01:21 UTC, goyounha11 commented on src/test/java/com/bnc/main/member/service/DefaultMemberServiceTest.java
> +
유저 번호로 조회 성공이 필요할까요?

2022-05-31 01:53 UTC, jy98102 commented on src/test/java/com/bnc/main/member/controller/MemberRestControllerTest.java
> +                .andDo(print());
+ 에서 , 로 바꾸고 테스트 돌려봤는데 Status expected:<200> but was:<404>
Expected :200
Actual   :404

2022-06-01 13:03 UTC, mumura commented on src/test/java/com/bnc/main/member/service/DefaultMemberServiceTest.java
> +
레스트 컨트롤러에서 아이디로 조회해서 유저 번호 조회 테스트를 했어용 보니깐 아이디 조회가 있네용 삭제하겠습니당!

2022-06-01 13:27 UTC, closed without merging